### ISSUE TITLE
Including omnipay classes fails 

### ISSUE THREAD

**Issue by nimeso** [silverstripe/silverstripe-omnipay#102]
I've installed 2.00 branch and still have issues with the vendor folder structure or something? 

Fatal error: Class 'Omnipay\Common\CreditCard' not found in /home/blipper/public_html/omnipay/code/services/PurchaseService.php on line 151

The vendor folder looks like:
```php
omnipay
    common
        src
             Omnipay
                 Common
                      CreditCard.php
                      OtherClasses.php
                      ....
        tests
             stuff
             .....
```
Looks strange to me?

Any help would be great :)

@markguinn help a (stupid) brother out? ;)

**Comment by markguinn** [comment]
Hmm. That sounds like something may be wonky with your composer autoloader? A couple things I would try (after flushing and/or wiping silverstripe-cache) would be running `composer dump-autoload` and if that doesn't work, try deleting the vendor folder entirely and run `composer update` or `composer install`.

**Comment by nimeso** [comment]
Still no luck at all @markguinn :( I ended up deleting the vendor folder, omnipay, framework and cms (just to be sure)
Thanks heaps for your help. This is holding a project back so I really need to work it out.

```php
[Warning] array_merge() [function.array-merge]: Argument #1 is not an array
POST /~blipper/api/Buy
Line 41 in /home/blipper/public_html/omnipay/code/services/PurchaseService.php

$gatewaydata = array_merge($data,array(
34 			'card' => $this->getCreditCard($data),
35 			'amount' => (float) $this->payment->MoneyAmount,
36 			'currency' => $this->payment->MoneyCurrency,
37 			//set all gateway return/cancel/notify urls to PaymentGatewayController endpoint
38 			'returnUrl' => $this->getEndpointURL("complete", $this->payment->Identifier),
39 			'cancelUrl' => $this->getEndpointURL("cancel", $this->payment->Identifier),
40 			'notifyUrl' => $this->getEndpointURL("notify", $this->payment->Identifier)
41 		));
42 		
43 		if(!isset($gatewaydata['transactionId'])){
44 			$gatewaydata['transactionId'] = $this->payment->Identifier;
45 		}
46 
47 		$request = $this->oGateway()->purchase($gatewaydata);
```
and then this:
```php
[User Error] Uncaught Omnipay\Common\Exception\RuntimeException: Class '\Omnipay\PxPayGateway\Gateway' not found
POST /~blipper/api/Buy
Line 105 in /home/blipper/public_html/vendor/omnipay/common/src/Omnipay/Common/GatewayFactory.php

* @param HttpRequest|null     $httpRequest A Symfony HTTP Request implementation
97      * @throws RuntimeException                 If no such gateway is found
98      * @return GatewayInterface                 An object of class $class is created and returned
99      */
100     public function create($class, ClientInterface $httpClient = null, HttpRequest $httpRequest = null)
101     {
102         $class = Helper::getGatewayClassName($class);
103 
104         if (!class_exists($class)) {
105             throw new RuntimeException("Class '$class' not found");
106         }
107 
108         return new $class($httpClient, $httpRequest);
109     }
110 
111     /**
```
My method looks like this... Just for testing (does it matter that $data is currently empty... what should $data be?)

```php
public function Buy($data){

		$payment = Payment::create()->init("PxPayGateway", 100, "NZD");
	    $response = PurchaseService::create($payment)
	        ->setReturnUrl($this->Link('complete'))
	        ->setCancelUrl($this->Link()."?message=payment cancelled")
	        ->purchase($data);

		Debug::dump($response);
		exit();

	}
```

Cheers heaps!

**Comment by nimeso** [comment]
@markguinn I added in some test $data but still no luck:

```php
public function Buy($data){
		
		$data = array(
			"transactionId" => "TEST4814",
			"firstName" => "Jamie",
			"lastName" => "Barker",
			"email" => "jamie@plattar.com",
			"company" => "none",
			"billingAddress1" => "42 McCarthy Street",
			"billingAddress2" => "Hoon Hey",
			"billingCity" => "Christchurch",
			"billingPostcode" => "8025",
			"billingState" => "Cantubary",
			"billingCountry" => "NZ",
			"billingPhone" => "4565678",
			"shippingAddress1" => "42 McCarthy Street",
			"shippingAddress2" => "Hoon Hey",
			"shippingCity" => "Christchurch",
			"shippingPostcode" => "8025",
			"shippingState" => "Cantubary",
			"shippingCountry" => "NZ",
			"shippingPhone" => "4565678"
		);

		$payment = Payment::create()->init("PxPayGateway", 100, "NZD");
	    $response = PurchaseService::create($payment)
	        ->setReturnUrl($this->Link('complete'))
	        ->setCancelUrl($this->Link()."?message=payment cancelled")
	        ->purchase($data);

		Debug::dump($response);
		exit();

	}
```
Which is better :) BUT I still get the Class not found errors :(

```php
[User Error] Uncaught Omnipay\Common\Exception\RuntimeException: Class '\Omnipay\PxPayGateway\Gateway' not found
POST /~blipper/api/Buy
Line 105 in /home/blipper/public_html/vendor/omnipay/common/src/Omnipay/Common/GatewayFactory.php
```

**Comment by markguinn** [comment]
@nimeso can you confirm that you're explicitly requiring the pxpay gateway from composer.json? Omnipay 2.0 doesn't include all the gateways by default anymore.

**Comment by sajansharmanz** [comment]
@markguinn I am also getting this error of Silverstripe failing to obtain the class

`[User Error] Uncaught Omnipay\Common\Exception\RuntimeException: Class '\Omnipay\\Gateway' not found
GET /donation-test/
Line 105 in C:\wamp\www\donation-test\vendor\omnipay\common\src\Omnipay\Common\GatewayFactory.php`

I have explicitly required both the 'Manual' and 'PayPal' gateways from composer.json. They have been downloaded to the `vendor/omnipay/` folder. I have also tested deleting the entire vendor folder and running a `composer install`

**Comment by markguinn** [comment]
What version of omnipay and silvershop are you running?

**Comment by sajansharmanz** [comment]
I was using the Omnipay 2.0-alpha release (2.0 branch im assuming). Im actually attempting to create a donation page using just the omnipay-module, however, i got as far as installing the module + setting up the yaml file before it started throwing this error when calling the GatewayFieldsFactory

**Comment by bummzack** [comment]
@sajansharmanz You probably got this error because you call a method on `GatewayFieldsFactory` without specifying your target gateway first… Have you tried: `$factory = new GatewayFieldsFactory('PayPal')` ?

**Comment by sajansharmanz** [comment]
@bummzack when i use 
`$factory = new GatewayFieldsFactory('PayPal')` 

it throws another error 
`[User Error] Uncaught Omnipay\Common\Exception\RuntimeException: Class '\Omnipay\PayPal\Gateway' not found
GET /donation-test/
Line 105 in C:\wamp\www\donation-test\vendor\omnipay\common\src\Omnipay\Common\GatewayFactory.php`

If i use `$factory = new GatewayFieldsFactory('PayPal_Express')` it doesn't throw any errors?

To be honest I am completely out of my depth trying this, not sure if i'm doing it right. Is there any reading materials to learn the basics of Payment Gateways and their integration that you recommend? Fairly new to these and not sure how they actually work completely

**Comment by bummzack** [comment]
You're right, that was my bad. It should be `PayPal_Express`!

As for reading material… if you want to understand how the gateways work, best read the omnipay documentation: https://github.com/thephpleague/omnipay

The parameters needed in configuration depend on the actual Gateways. PayPal requires username, password and signature, while other gateways (such as Stripe) only require an API key. I suggest you use the 2.0.x-dev branch of this module and read the documentation here: https://github.com/silverstripe/silverstripe-omnipay/tree/2.0

**Comment by RMahanor** [comment]
[10-Mar-2018 07:26:21 UTC] PHP Fatal error:  Uncaught exception 'Omnipay\Common\Exception\RuntimeException' with message 'Class '\Omnipay\PayUBiz\Gateway' not found' in /home/ivybawok/public_html/ivystays.com/wp-content/plugins/wp-booking-management-system/shinetheme/libraries/vendor/omnipay/common/src/Omnipay/Common/GatewayFactory.php:105


Same problem here plz helpus

**Comment by bummzack** [comment]
@RMahanor You're probably at the wrong place here. This is an addon for the SilverStripe CMS and from your error message it looks like you're using Wordpress.
