### ISSUE TITLE
Should the manual payment be a requirement?

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-omnipay#111]
The documentation states:
> If no allowed gateways are configured, then the module will default to providing the "Manual" gateway.

Either we remove this part from the documentation and alter `GatewayInfo::getSupportedGateways` to not return "Manual" by default, or we add "omnipay/manual" as composer dependency.

@markguinn, @anselmdk, @wilr Thoughts?

**Comment by markguinn** [comment]
I think it makes sense to throw an exception if no gateway is configured.

**Comment by bummzack** [comment]
Closed via #112
