### ISSUE TITLE
Should PaymentController be a part of this module?

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-omnipay#117]
I noticed that the `2.0` branch is based off `1.1.1`, but there has been further development in a `1.2` branch.

The most notable addition to `1.2` is the introduction of a `PaymentController` which seems to provide some application-logic to do payments.

Should we provide some basic means to do payments out of the box with this module? 

Personally, I'm not in favor of adding this. Application logic should be in the applications (eg. Shops or other modules that make use of the omnipay-module). I'd rather spend the time to improve the quality of the existing featureset, instead of providing more features. I'd also rather improve documentation for application-developers, so that they can better integrate the module.

I'm interested to hear opinions on this though.

**Comment by markguinn** [comment]
Yes, last time I talked with Jeremy about this he said it's a work in progress but has no plans on completing it. My vote would be to abandon it. Maybe we could even rename the branch "abandoned-1.2" or something so it doesn't confusing things on packagist, but someone could pick up the work and/or pull it into it's own module if they want to.

**Comment by bummzack** [comment]
Closed in favor of abandoning the changes started in the 1.2 branch
