### ISSUE TITLE
Should this module contain UI components?

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-omnipay#126]
I'm currently working on #118 to allow partial captures and refunds. This is going to introduce a more complex UI, since we need dialogs to enter partial amounts etc.
This will potentially also include more dependencies, such as the betterbuttons-module and maybe JS libraries.

I'd like to hear your opinion whether or not UI components to deal with Payments should be part of this module?

My gut feeling is to move the UI components to a separate module. 
Pros:

- The silverstripe-omnipay module will be less cluttered and only provide the logic to integrate your silverstripe application with omnipay.
- With upcoming changes to UI elements in SilverStripe (React, bootstrap etc.), this module will be unscathed by this.
- Modules that build upon the omnipay module (shops etc.) are free to build their own UI for the services or install the existing one.

Cons:

- Another module that has to be maintained (could just as well be a pro, as the UI module can then have another release-cycle than the omnipay-module)
- Slightly more complex to install

What would a separate UI-module mean?

- Create a new module, `silverstripe-omnipay-ui`. I could maintain this module, or it could also go into the `silverstripe` organization, which would be nicer.
- Add the new module as a suggestion in composer.json
- Move all UI related stuff to that new module (that includes the newly added GridField actions in 2.0 and most likely also the PaymentAdmin).

What do you think?

**Comment by markguinn** [comment]
My vote would be to err on the side of separation of concerns. I usually end up removing PaymentAdmin anyway. That said, I'd be fine with keeping some UI in the Omnipay module too. The main reason I'd be for separating them is if you need to require betterbuttons or something (although, I'd be surprised to find anyone not using that module at this point).

**Comment by sanderha** [comment]
I think UI should be in a separate module if possible, specially because of the upcoming reactJS/Bootstrap changes in SilverStripe.

**Comment by bummzack** [comment]
I've removed UI components with PR #130 and started a new Module that adds these here: https://github.com/bummzack/silverstripe-omnipay-ui

Should/can we move this also to the SilverStripe Organization? @markguinn, @anselmdk, @wilr ?

**Comment by anselmdk** [comment]
I think that'd make sense.

**Comment by anselmdk** [comment]
@bummzack wouldn't it make sense to suggest it in `silvershop-core` as well ad adding to the README that the option for the UI exists?
