### ISSUE TITLE
Omnipay v1.1.0 - PayPal functionality could be discontinued next year 

### ISSUE THREAD

**Issue by imprezio** [silverstripe/silverstripe-omnipay#131]
Hi there,

Paypal has alerted me that my shop using this module needs to :  "Discontinue Use of GET Method for Classic NVP/SOAP APIs" by 30 June 2017.

More information on the following link: https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1927&viewlocale=en_US

The latest version of omnipay (2.0) has this fixed up, though this module's version of omnipay (1.1) is still using the GET method to send Paypal requests.

Could someone please shed some more light on this issue as I'm still a bit inexperienced when it comes to this sort of stuff.

Cheers

**Comment by wilr** [comment]
See the 2.0 branch for the omnipay 2.* support. That should resolve it.
