### ISSUE TITLE
How to make your model Payable?

### ISSUE THREAD

**Issue by outdoorsnz** [silverstripe/silverstripe-omnipay#133]
What is the correct way to make my model payable? I have a VehiclePageBookings model that stores all the booking details and gets paid for.

I tried this in app.yml:
#Payable extension
VehiclePageBookings:
  extensions:
    - Payable

But don't see any relational fields added.

Thanks
Regards
Scott

**Comment by wilr** [comment]
Payable should add a tab for payments in the CMS to create attached 'Payment' objects. Make sure you're done a dev/build to rebuild the database

**Comment by outdoorsnz** [comment]
Hi Wilr. Thanks for your reply.

Doesn't seem to create the Payments in the CMS or any relation fields. Here is a snippet of my code:
VehiclePageBookings:
class VehiclePageBookings extends DataObject
{...
Not setting this here:
//        private static $has_many = array(
//            'Payable' => 'Payable'            
//        );

As thinking this will do the same in app.yml:
#Payable extension
VehiclePageBookings:
  extensions:
    - Payable

And my ShopPayment:
class ShopPayment extends DataExtension
{
    private static $has_one = array(
        'VehiclePageBookings' => 'VehiclePageBookings',
    );
   ...
Must be missing something.

**Comment by outdoorsnz** [comment]
Update.

Adding:
Payment:
    has_one:
        VehiclePageBookings: VehiclePageBookings

Instead of ShopPayment extensions does create the has_one on the payments side (VehiclePageBookingsID field), but not on the other has_many end.

**Comment by markguinn** [comment]
@outdoorsnz how are you using this? Is this with SilverShop? Or is it another module or your own setup? Have you seen Roman's silverstripe-omnipay-ui module (https://github.com/bummzack/silverstripe-omnipay-ui)?

**Comment by bummzack** [comment]
Your payable object will have a `has_many` relation to `Payment`, introduced via the `Payable` extension, but we can't know about the other side of the relation… so the `has_one` component has to be added by yourself, either via YAML or an Extension. See: https://github.com/silverstripe/silverstripe-omnipay#make-your-model-payable

Here's how the config would look like to make `VehiclePageBookings` payable:

```yaml
VehiclePageBookings:
  extensions:
    - Payable
Payment:
  has_one:
    VehiclePageBookings: VehiclePageBookings
```

If you're using the 2.0 branch, all the UI components have been removed and added to an external module: https://github.com/bummzack/silverstripe-omnipay-ui

**Comment by outdoorsnz** [comment]
@markguinn This for my own setup. Basically the user does a quote for a vehicle, fills out a booking form and is fired off for hosted payment. Didn't know about the UI module.

I'm really just wanting to set the relation side correct, so that VehiclePageBookingsID gets added to the payments table.

@bummzack Using the 1.1 branch - master.  Have added YAML code as above. VehiclePageBookingsID field gets created. But when I make a booking, VehiclePageBookingsID doesn't get created. I guess it doesn't know anything about what the ID is, so do I need to pass the ID in somewhere. i.e. as a hidden field? Thanks :-)

**Comment by bummzack** [comment]
@outdoorsnz Yeah, the relation isn't established automatically. I guess the simplest approach is to just set the `VehiclePageBookingsID` upon creating the `Payment` object?

**Comment by outdoorsnz** [comment]
Hi @bummzack. How would I create the VehiclePageBookingsID?
Tried this:
$payment = Payment::create()->init("PaymentExpress_PxPay", "100", "NZD");
$payment->VehiclePageBookings($reg->ID);

But says method doesn't exist. What is the best approach? Thanks.

**Comment by outdoorsnz** [comment]
Update. I did get this to set the VehiclePageBookingsID. $payment->VehiclePageBookingsID=$reg->ID;

Had done a /dev/build/?flush=1, but also needed to flush the cache.

What is the best way to load the payment once you get a successful payment and redirected to confirm url? Pass a random string?

**Comment by bummzack** [comment]
You can do:
```
$payment->VehiclePageBookingsID = $reg->ID;
```
or
```
$reg->Payments()->add($payment);
```
…assuming that `$reg` is your `VehiclePageBookings` instance.

These are basic SilverStripe ORM questions though. They'd be better suited for a question on the SilverStripe forums, stackoverflow or [chat](https://gitter.im/silverstripe/silverstripe-omnipay)

Not sure what you mean by "load the payment". Do you want to display payment information to the user? Have you read this: https://github.com/silverstripe/silverstripe-omnipay#make-a-purchase ?

**Comment by outdoorsnz** [comment]
The customer gets redirected back to the confirmation (confirm controller) page and will display payment confirmation details to the user. i.e.
$response = PurchaseService::create($payment)
                        ->setReturnUrl($this->Link()."confirm/")
                        ->setCancelUrl($this->Link()."?message=payment cancelled")
                        ->purchase($dataform);
                    $response->redirect();

What I'm wanting to know how is how to access the payment details to display. i.e. booking reference etc.

Reading that link, I think it has something to do with extend and onCaptured hook.

**Comment by bummzack** [comment]
I see. It's not something that is built into the module, but you could simply add the Payment Identifier to the return-url, like this:
```
->setReturnUrl($this->Link('confirm/' . $payment->Identifier);
```

And then in your `confirm` action, do something like:

```php
public function confirm()
{
	$id = $this->request->param('ID');
	return array(
		'Payment' => Payment::get()->filter('Identifier', $id)->first()
	);
}
```

In your template you can then access `$Payment` to get the information you need

**Comment by outdoorsnz** [comment]
I tried that, but Identifier doesn't show at all in the redirected URL or in param('ID').

Is that because the Identifier hasn't been set at this point? i.e. here
->setReturnUrl($this->Link('confirm/' . $payment->Identifier));

**Comment by bummzack** [comment]
The identifier will be created upon writing the payment. You have to make sure that the payment was written to the DB first. `$payment->write()`.

**Comment by outdoorsnz** [comment]
Awesome thanks for all your help @bummzack . Got most of it sorted out now.

**Comment by bummzack** [comment]
Glad I could help. Can we close this issue then?

**Comment by outdoorsnz** [comment]
Yup you can close this now. :-)
