### ISSUE TITLE
Issue when going live

### ISSUE THREAD

**Issue by namnn96** [silverstripe/silverstripe-omnipay#137]
Hi,

As I use the module, sandbox testing is fine but when I replace with live api username, password and signature, the page does not redirect me to paypal anymore.

As looking into the module, I couldn't find a place for paypal endpoint url. 
Just one question, aside from changing the username, password and signature, is there anything else I need to change when going live?

Thanks in advance

**Comment by bummzack** [comment]
Aside from username, password and signature, you'll also have to set `testMode: false`.

I think the [chat](https://gitter.im/silverstripe/silverstripe-omnipay) would be better suited for issues like yours.

**Comment by namnn96** [comment]
I have already set it to false, but it doesn't work. I get the live credentials from Selling tool > API Access  and username is similar to sandbox, would that be normal
