### ISSUE TITLE
Depreciated method GatewayInfo::getParameters still called

### ISSUE THREAD

**Issue by hailwood** [silverstripe/silverstripe-omnipay#139]
> ErrorException thrown with message "SilverStripe\Omnipay\GatewayInfo::getParameters is deprecated. Please refrain from setting Gateway parameters under Payment. Use GatewayConfig instead (see docs). Called from SilverStripe\Omnipay\Service\PaymentService->oGateway."

I'll look into a fix for it now since it's er... stopping me dead in my tracks. But thought I'd post it incase it's already been fixed?

**Comment by hailwood** [comment]
Looks like it was introduced in https://github.com/silverstripe/silverstripe-omnipay/pull/105

**Comment by hailwood** [comment]
Ok, so I'm confused now,
It looks like It's because I had an old form setup with the version 1 syntax which is fine, I've moved things over so they're under GatewayConfig instead, but the Paypal docs say GatewayInfo?

https://github.com/silverstripe/silverstripe-omnipay/blob/master/docs/en/PayPalExpressSetup.md

**Comment by hailwood** [comment]
Alrighty, so I believe the error message is incorrect and it should say GatewayInfo?

**Comment by bummzack** [comment]
You're right. It should be GatewayInfo. I'll fix this. Thanks for the heads-up.

**Comment by bummzack** [comment]
It's fixed in master. Is it ok to close this?
