### ISSUE TITLE
Remove credit-card data from log

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-omnipay#144]
When using verbose logging, credit-card data will show up in the log. This should be avoided.

Possible solution: Hide CC-Data from the Log when SilverStripe is in Live environment.

**Comment by ReeceA** [comment]
Something to keep in the back of your mind, in some countries (Australia for example) it's illegal to store unmasked credit card information in any fashion whatsoever.

**Comment by bummzack** [comment]
Fixed via #180
