### ISSUE TITLE
Potentially ambiguous field names

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-omnipay#146]
tl;dr Change field `number` and `name` that represents a credit card number and name to `cardNumber` and `cardName`

This could cause ambiguity when you `$fields->merge($gatewayFactory->getFields());`

Might be worth changing it to something more semantic such as `cardNumber` and `cardName` so the chance of conflicts with the merge above are reduced.

I've had to give my original fields less-semantic names due to this (not like it's a big issue)

Feel free to close this issue if you think otherwise :)

**Comment by bummzack** [comment]
I agree that this isn't ideal, but the field-names just map directly to the properties of the Omnipay CreditCard class. Renaming them would also mean to introduce a proper mapping from the form-field-names to the omnipay properties.

There's so many use-cases for front-end forms and the GatewayFieldsFactory just provides the bare minimum. It should be replaced with a more versatile solution…

**Comment by bummzack** [comment]
Closed via #148
