### ISSUE TITLE
Expiry Month & Expiry Year To Not Have A Default

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-omnipay#147]
As of the moment, expiry month defaults to "01 - January" and year to the current year.

Would be nice if both of these fields would default to "Please select ..." for JS onChange client validation

or default to current month at least so it always has a valid expiry date thats not in the past

**Comment by bummzack** [comment]
I agree. Can you create a PR for this?

**Comment by zanderwar** [comment]
Sure can, give me a few days (flat out at work)
