### ISSUE TITLE
Allow administrators to complete payment

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#16]
Administrators sometimes need to make/complete a payment. The customer may give credit card details over the phone, or send through some kind of manual payment, and this needs to be recorded/updated by an administrator of the application.

An interface will need to be created to allow completing (possibly also creating) payments via any type of gateway. This interface should be accessible from the CMS.

**Comment by bummzack** [comment]
This library is moving away from having UI components and focuses on the payment API. I'm going to add this issue at https://github.com/bummzack/silverstripe-omnipay-ui/issues/8
