### ISSUE TITLE
worldpay callback error error

### ISSUE THREAD

**Issue by sparkcom** [silverstripe/silverstripe-omnipay#190]
Hello, 

Wonder if this is a bug or if I have missed something? 

`

ERROR [UNKNOWN TYPE, ERRNO ]: SilverStripe\Omnipay\Model\Message\CompletePurchaseError (WorldPay)
IN POST /paymentendpoint/e848096b821a982cffc90ccf880052/notify?msgType=authResult&installation=*****
 

ERROR [User Warning]: Couldn't set response type to 500 because of output on line 358 of /home/***/vendor/silverstripe/framework/src/Control/HTTPResponse.php
IN POST /paymentendpoint/e848096b821a982cffc90ccf880052/notify?msgType=authResult&installation=1281322
Line 337 in /home/****/vendor/silverstripe/framework/src/Control/HTTPResponse.php

Source
======
  328:             // It's critical that these status codes are sent; we need to report a failure if not.
  329:             user_error(
  330:                 sprintf(
  331:                     "Couldn't set response type to %d because of output on line %s of %s",
  332:                     $this->getStatusCode(),
  333:                     $line,
  334:                     $file
  335:                 ),
  336:                 E_USER_WARNING
* 337:             );
  338:         }
  339:     }
  340: 
  341:     /**
  342:      * Output body of this response to the browser
  343:      */

Trace
=====
user_error(Couldn't set response type to 500 because of output on line 358 of /home/***/vendor/silverstripe/framework/src/Control/HTTPResponse.php, 512)
HTTPResponse.php:337

SilverStripe\Control\HTTPResponse->outputHeaders()
HTTPResponse.php:282

SilverStripe\Control\HTTPResponse->output()
index.php:27

NOK`

**Comment by sparkcom** [comment]
it's ok. The callback password seems not setup probably.

**Comment by mlewis-everley** [comment]
@bummzack / @dhensby I think this can be closed?
