### ISSUE TITLE
Composer wont work for silverstripe 4.2.1

### ISSUE THREAD

**Issue by liamchowneydev** [silverstripe/silverstripe-omnipay#200]
I have tried many ways to install this module with composer:
composer require silvershop/core
composer require silvershop/core ^3
composer require silvershop/core ^3@dev

I know its not my composer because I have managed to install other modules.

  Problem 1
    - silverstripe/cms 3.1.0-beta1 requires silverstripe/framework 3.1.x-dev -> no matching package found.
    - Conclusion: don't install silvershop/core 2.4.0
    - Conclusion: don't install silvershop/core 2.x-dev|remove silverstripe/cms 4.2.1
    - Conclusion: don't install silvershop/core 2.x-dev|don't install silverstripe/cms 4.2.1
    - Installation request for silvershop/core ^2.4 -> satisfiable by silvershop/core[2.4.0, 2.x-dev].
    - silvershop/core 2.x-dev requires silverstripe/cms ^3.1 -> satisfiable by silverstripe/cms[3.1.0, 3.1.0-beta1, 3.1.0-beta2, 3.1.0-beta3, 3.1.0-rc1, 3.1.0-rc2, 3.1.0-rc3, 3.1.1, 3.1.10, 3.1.10-rc1, 3.1.10-rc2, 3.1.11, 3.1.11-rc1, 3.1.12, 3.1.13, 3.1.13-rc1, 3.1.14, 3.1.14-rc1, 3.1.15, 3.1.16, 3.1.16-rc1, 3.1.17, 3.1.17-rc1, 3.1.17-rc2, 3.1.18, 3.1.18-rc1, 3.1.18-rc2, 3.1.19, 3.1.19-rc1, 3.1.2, 3.1.2-rc1, 3.1.20, 3.1.20-rc1, 3.1.20-rc2, 3.1.21, 3.1.3, 3.1.3-rc1, 3.1.3-rc2, 3.1.4, 3.1.4-rc1, 3.1.5, 3.1.5-rc1, 3.1.6, 3.1.6-rc1, 3.1.6-rc2, 3.1.6-rc3, 3.1.7, 3.1.7-rc1, 3.1.8, 3.1.9, 3.1.9-rc1, 3.2.0, 3.2.0-beta1, 3.2.0-beta2, 3.2.0-rc1, 3.2.0-rc2, 3.2.1, 3.2.1-rc1, 3.2.1-rc2, 3.2.2, 3.2.2-rc1, 3.2.2-rc2, 3.2.3, 3.2.3-rc1, 3.2.3-rc2, 3.2.4, 3.2.4-rc1, 3.2.5, 3.2.5-rc1, 3.2.5-rc2, 3.2.6, 3.3.0, 3.3.0-beta1, 3.3.0-rc1, 3.3.0-rc2, 3.3.0-rc3, 3.3.1, 3.3.1-rc1, 3.3.1-rc2, 3.3.2, 3.3.2-rc1, 3.3.3, 3.3.3-rc1, 3.3.3-rc2, 3.3.4, 3.4.0, 3.4.0-rc1, 3.4.1, 3.4.1-rc1, 3.4.1-rc2, 3.4.2, 3.4.3, 3.4.3-rc1, 3.4.4, 3.4.4-rc1, 3.4.5, 3.4.5-rc1, 3.4.6, 3.4.6-rc1, 3.4.6-rc2, 3.5.0, 3.5.0-rc1, 3.5.0-rc2, 3.5.0-rc3, 3.5.1, 3.5.1-rc1, 3.5.1-rc2, 3.5.2, 3.5.2-rc1, 3.5.3, 3.5.3-rc1, 3.5.4, 3.5.4-rc1, 3.5.5, 3.5.5-beta1, 3.5.5-beta2, 3.5.6, 3.5.6-rc1, 3.5.7, 3.5.8, 3.5.8-rc1, 3.5.x-dev, 3.6.0, 3.6.0-beta1, 3.6.0-beta2, 3.6.0-rc1, 3.6.1, 3.6.1-alpha1, 3.6.1-alpha2, 3.6.2, 3.6.2-beta1, 3.6.2-beta2, 3.6.3, 3.6.3-rc2, 3.6.4, 3.6.5, 3.6.6, 3.6.6-rc1, 3.6.x-dev, 3.7.0, 3.7.1, 3.7.1-rc1, 3.7.x-dev, 3.x-dev].
    - Can only install one of: silverstripe/cms[3.1.0, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.0-beta2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.0-beta3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.0-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.0-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.0-rc3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.10, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.10-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.10-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.11, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.11-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.12, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.13, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.13-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.14, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.14-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.15, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.16, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.16-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.17, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.17-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.17-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.18, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.18-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.18-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.19, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.19-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.2-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.20, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.20-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.20-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.21, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.3-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.3-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.4, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.4-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.5, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.5-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.6, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.6-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.6-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.6-rc3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.7, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.7-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.8, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.9, 4.2.1].
    - Can only install one of: silverstripe/cms[3.1.9-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.0, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.0-beta1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.0-beta2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.0-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.0-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.1-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.1-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.2-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.2-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.3-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.3-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.4, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.4-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.5, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.5-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.5-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.2.6, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.0, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.0-beta1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.0-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.0-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.0-rc3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.1-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.1-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.2-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.3-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.3-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.3.4, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.0, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.0-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.1-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.1-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.3-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.4, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.4-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.5, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.5-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.6, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.6-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.4.6-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.0, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.0-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.0-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.0-rc3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.1-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.1-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.2-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.3-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.4, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.4-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.5, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.5-beta1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.5-beta2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.6, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.6-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.7, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.8, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.8-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.5.x-dev, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.0, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.0-beta1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.0-beta2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.0-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.1-alpha1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.1-alpha2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.2-beta1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.2-beta2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.3, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.3-rc2, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.4, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.5, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.6, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.6-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.6.x-dev, 4.2.1].
    - Can only install one of: silverstripe/cms[3.7.0, 4.2.1].
    - Can only install one of: silverstripe/cms[3.7.1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.7.1-rc1, 4.2.1].
    - Can only install one of: silverstripe/cms[3.7.x-dev, 4.2.1].
    - Can only install one of: silverstripe/cms[3.x-dev, 4.2.1].
    - Installation request for silverstripe/cms (locked at 4.2.1) -> satisfiable by silverstripe/cms[4.2.1].

**Comment by bummzack** [comment]
This seems to be an error with silvershop. See: https://github.com/silvershop/silvershop-core/issues/671
