### ISSUE TITLE
Incorrect expiryMonths in Dropdown

### ISSUE THREAD

**Issue by Leapfrognz** [silverstripe/silverstripe-omnipay#208]
Hi Guys.
GatewayFieldsFactory::getCardFields() will not generate a correct list of months. It will skip the month of February.

See https://stackoverflow.com/a/23938707
and https://derickrethans.nl/obtaining-the-next-month-in-php.html

the fix is to use the 1st day of the month, I believe php assumes the 30th.
```
$months[$x] = str_pad($x, 2, '0', STR_PAD_LEFT) . " - " . strftime('%B', mktime(0, 0, 0, $x, 1));
```

As far as I can tell, this is only an issue up until the 2.0 branch

**Comment by adrian-stein** [comment]
I am also having the same issue. Using the 2.3.0 branch.

It returns this for me

01 - January
02 - March
03 - March
04 - May
05 - May
06 - July
07 - July
08 - August
09 - October
10 - October
11 - December
12 - December

Has this always happened or something new. Are there any fixes to it?

**Comment by adrian-stein** [comment]
To follow up it is now working. So as Leapfrognz said above it must use the current day to find the other months, so it is broken when getting values for the days (28, 29, 30, 31) maybe or at least 31, as some months dont have that number of days.

**Comment by wilr** [comment]
Fixed in master.
