### ISSUE TITLE
Composer seems to install wrong version of omnipay/common

### ISSUE THREAD

**Issue by muppsy007** [silverstripe/silverstripe-omnipay#212]
Installing silverstripe-omnipay per docs as follows:

**composer require silverstripe/silverstripe-omnipay ^3@dev**

This installs the following:

> Package operations: 6 installs, 0 updates, 0 removals
>   - Installing symfony/polyfill-php70 (v1.12.0): Downloading (100%)         
>   - Installing symfony/http-foundation (v3.4.32): Downloading (100%)         
>   - Installing symfony/event-dispatcher (v2.8.50): Downloading (100%)         
>   - Installing guzzle/guzzle (v3.9.3): Downloading (100%)         
>   - Installing omnipay/common (2.5.2): Downloading (100%)         
>   - Installing silverstripe/silverstripe-omnipay (3.0.0-alpha2): Downloading (100%)     

Note that version of omnipay/common is 2.5.2 despite this module's composer.json set to require ^3.

Impact of this is when I attempt to install gatway adapters, they cannot install as they expect a higher version of omnipay/common.

**composer require omnipay/stripe**

>  Problem 1
>     - omnipay/stripe 3.1.x-dev requires omnipay/common ^3 -> satisfiable by omnipay/common[3.0.x-dev, v3.0-RC1, v3.0-RC2, v3.0-alpha.1, v3.0-alpha.2, v3.0-alpha.3, v3.0-alpha.4, v3.0-beta.1, v3.0-beta.2, v3.0-beta.3, v3.0.0, v3.0.1, v3.0.2].

I have tried to update omnipay/common myself, but I get this instead:

**composer require omnipay/common ^3** 
>  - omnipay/common v3.0.2 requires php-http/client-implementation ^1 -> no matching package found.
>  - omnipay/common v3.0.1 requires php-http/client-implementation ^1 -> no matching package found.
>  - omnipay/common v3.0.0 requires php-http/client-implementation ^1 -> no matching package found.

But big question is why this module's requirements are being ignored right from the get go?

**Comment by muppsy007** [comment]
Cancel that. I found that installing omnipay and the adapter first, then this module, resolves this.

- composer require league/omnipay:^3 omnipay/stripe
- composer require silverstripe/silverstripe-omnipay ^3@dev

Note that omnipay/stripe may be different for you depending on what adapter you are using.

**Comment by kinglozzer** [comment]
Just dropping by to say we experienced this same issue last week, the solution above (uninstall `silverstripe-omnipay`, install `league/omnipay` and gateway, then re-install `silverstripe-omnipay`) worked for us.

I’m not sure if this is a bug with this module, or just a composer quirk. I also can’t help but wonder if tagging a `3.0.0` stable release will fix this...

**Comment by HARVS1789UK** [comment]
I also experienced this is when installing a separate module which has `silverstripe-omnipay` as a requirement (`silvershop/core`).

I was unable to install the `omnipay/paypal` gateway or any other gateways which require `omnipay/common` version `3` or higher.

**Comment by muppsy007** [comment]
Hi @HARVS1789UK @kinglozzer. I have reopened issue as I self closed when I found a work around. Sounds like there might be something here for maintainers to look at. I'll let them decide to close it.

Thanks for adding info.

**Comment by joshdillner** [comment]
@HARVS1789UK I had the same issue with `silvershop`, but also got it going by removing `silverstripe-omnipay` AND any remaining `omnipay` modules first, before reinstalling 

1. `league/omnipay:^3`
2. `omnipay/stripe`
3. `silverstripe/silverstripe-omnipay ^3@dev`

**Comment by kinglozzer** [comment]
Does anyone have any objections to tagging the current `master` branch as `3.0.0`? We have a couple of production sites that have been running `3.0.0-alpha3` without any issues

cc @bummzack

**Comment by bummzack** [comment]
@kinglozzer I created the `3.0.0` release. Hope that solves some of the issues people are having.
