### ISSUE TITLE
Missing option to disable logToFile

### ISSUE THREAD

**Issue by CMeldgaard** [silverstripe/silverstripe-omnipay#214]
Im missing a option to disable `logToFile` in the abstract PaymentService class - i can see the idea when working locally, but because it logs to the silverstripe error log file, it also triggers Sentry error logging - meaning everytime a purchase is made i get 4 errors registered.

My suggestion would be to wrap `$this->logToFile($output, $type);` in a if-statement to check if config allows for logging.

**Comment by tractorcow** [comment]
You can probably try registering a `NullLogger` as the `Psr\Log\LoggerInterface` service.

I would really rather just have an option to throw exceptions rather than trying to mangle them (poorly) in code.

**Comment by tractorcow** [comment]
```
---
Name: logging-payment
After:
  - '#omnipay-logging'
---
# Disable garbage logging
SilverStripe\Core\Injector\Injector:
  SilverStripe\Omnipay\Logger:
    class: 'Psr\Log\NullLogger'
```

**Comment by kinglozzer** [comment]
I ran into the same issue (also with Sentry!) - options were to leave logging on and risk accidentally logging payment info in Sentry, or disable logging entirely and potentially leave exceptions un-reported. This is what I’ve come up with https://github.com/silverstripe/silverstripe-omnipay/pull/229, and the config for it:

```yml
---
Name: payment-logging
After:
  - '#omnipay-logging'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Omnipay\Logger:
    class: 'Psr\Log\NullLogger'
  SilverStripe\Omnipay\ExceptionLogger: '%$Psr\Log\LoggerInterface'
```
