### ISSUE TITLE
Upgrade to omnipay 2+

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#23]
This will require rewriting some of the way unit tests retrieve mock data. It is currently a hard-coded path, but will need to shift towards retrieving it from the appropriate composer package automatically.

Looking at the ominpay library tests should help here.

This will bring a few improvements, including being able to pass item descriptions to gateways: https://github.com/omnipay/omnipay/releases/tag/v2.0.0

If their github [releases page](https://github.com/thephpleague/omnipay/releases) is anything to go by, it looks like there are no further breaking changes, and as such could upgrade straight to omnipay 2.3.x

see also
http://omnipay.thephpleague.com/changelog/

**Comment by JorisDebonnet** [comment]
Soo... this isn't expected any time soon, is it? :) I've got a payment processor that is supported by Omnipay 2, but not by Omnipay 1.1... Guess I'll have to change payment processors then, too bad though...

**Comment by bummzack** [comment]
How complex would it be to move the omnipay dependency to 2.0? From what it looks like, the API has remained pretty stable from 1.x to 2.x? Is it really just testing?

I think keeping the 1.x dependency is going to be a hindrance for this module as well as the shop module in general.

**Comment by markguinn** [comment]
@kinglozzer did you say you got it working with Omnipay 2? What's the state of that work? Any chance of a PR?

**Comment by kinglozzer** [comment]
@markguinn Current form is this: https://github.com/bigfork/silverstripe-omnipay/tree/omnipay-v2. I didn’t solve the issue of hardcoded paths, I just swapped them out to check that tests pass! We’ve currently got one site live running it, it only uses one gateway (Sagepay) but we haven’t had any issues at all so far.

IIRC there weren’t any major changes at all, just changes to how the packages/dependencies are set up - v2 upgrade guide is [here](http://omnipay.thephpleague.com/changelog/). We could also consider switching from requiring `omnipay/omnipay` (which automatically pulls in a number of gateways) to using `omnipay/common` (that doesn’t pull in _any_ - so devs have to manually add the gateways they want).

Happy to open a PR, not really sure how to fix up the test paths but it can’t be that difficult :)

**Comment by bummzack** [comment]
I would personally prefer to only include `omnipay/common`, but `omnipay/omnipay` is probably closer to what we have now with 1.1, where a lot of payment gateways come out of the box. It's just a bunch of unneeded classes for the most part though ;)

**Comment by kinglozzer** [comment]
I think we should go for the lighter `omnipay/common` and release it as `2.0.0`. This module currently *requires* the use of composer anyway, so I’m sure that anyone who knows how to use composer knows how to install their gateways of choice :)

We only need to `require-dev` a gateway or two for the unit tests and it should be good to go.

**Comment by bummzack** [comment]
Sounds good to me.

**Comment by markguinn** [comment]
This all sounds good to me. There is an unreleased 1.2 branch that @jedateach and @wilr had been working on, so I think we'd want to merge that in as well before tagging a 2.0 release. Jeremy, Will, any concerns about doing so?

**Comment by markguinn** [comment]
@jedateach or @wilr just pinging you one more time about the state of the 1.2 branch - is it still a work in progress or is it close to ready to release at all?

**Comment by markguinn** [comment]
Guys, I've created a 2.0 branch and pulled in @kinglozzer's changes. I've also reduced the composer requirement to `omnipay/common` and updated the docs. @bummzack if you've got any breaking changes to introduce on the translation front you can now PR against this branch. I don't imagine we need to hold off tagging 2.0 until SS 4.0 and Shop 2.0. If we get it to a better/stable place before then we could go ahead and tag it as the Omnipay 2.0 issue has caused people plenty of confusion.

Tests on the 1.2 branch don't appear to be passing at present so I've not merged that work into 2.0 yet, but it would be ideal to do that before actually tagging a release.

**Comment by jedateach** [comment]
Yeah, as far as I remember, the 1.2 version is unstable, and not thoroughly tested.

**Comment by bummzack** [comment]
@markguinn Thanks for this. I don't think the PayPal gateway should be a dev requirement though. Maybe just keep the dummy gateway there? I'm also having difficulties using the 2.0 branch in composer… I tried "2.0" and "dev-2.0" to no avail. Or am I just a composer-newbie? Maybe a tag (2.0-beta) or branch-alias would help?

**Comment by markguinn** [comment]
@bummzack it's more complicated than that even because shop currently requires ~1.1 which will then fail if you require omnipay 2.0. Since this is still very very early I don't feel good about tagging anything yet but you can use this syntax:

```
"burnbright/silverstripe-omnipay": "2.0.x-dev as 1.1",
```

I'll go ahead and bump the requirement in shop pre-emptively with the next point release, which is due around the end of the month anyway.

**Comment by markguinn** [comment]
I believe some of the tests reference fixtures from both paypal and pxpay (payment express) as well as manual, which is why I included those as dev dependencies. I don't think it hurts anything to have them in there but if you wanted them out it would mean refactoring several of the unit tests and possibly packaging those fixtures with this module. The advantage of having them external though is that they'll be maintained by someone else if the content changes. :)

**Comment by bummzack** [comment]
2.0 is looking good so far, there's an issue with the "Manual" gateway though… In Omnipay 2.x, the Manual Gateway only supplies `authorize` and `capture` methods, but omits `purchase` (which is actually correct, when you think about it).

The proper way to do this, would be to tackle #3 to support authorized payments. I'm neither an omnipay expert, nor do I have a lot of insight in the current architecture of this module to estimate the amount of work this would involve.

Gateways have methods to detect features, such as `supportsPurchase`. So a cheap fix would be to use `authorize` when `supportsPurchase` returns false.

What do you think?

**Comment by bummzack** [comment]
Closed via #107
