### ISSUE TITLE
Implement AuthorizeCaptureService (delayed purchase)

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#3]
The module should make provision for either making payment via purchase or authorise & capture.
All gateways provide purchase, but some allow authorize & capture.

The payment module could always go for authorise, if available.

**Comment by Sanderha** [comment]
Any info on when this would be implemented?

**Comment by jedateach** [comment]
Unfortunately, no. I'm not heavily involved with this project any more.

**Comment by markguinn** [comment]
@Sanderha we always welcome pull requests (which you might find easier than you'd think) or you could try posting a bounty for this issue and publicizing it on social media and the forums. Others have had decent luck at https://www.bountysource.com/

**Comment by bummzack** [comment]
Closed via #107
