### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#4]
We don't need to test the gateway handling...that is the job of omnipay.

Use either dummy payment or manual payment for tests. Not sure how to test `isRedirect == true` functionality.

Things that still need to be tested for 1.0 release:

 - [x] configuring gateways
 - [x] creating a payment
 - [x] state machine restrictions
 - [x] onsite and offsite gateway interactions (using mock responses)
 - [ ] dummy / manual gateways
 - [x] Payable extension
 - [x] logging: produce every type of PaymentMessage
 - [x] on-site missing credit card details
 - [ ] on-site invalid credit card details (expired, lhun fail, etc)
 - [ ] 0 or negative amounts

..as these are checked off, we may find that the system design may change a little

**Comment by bummzack** [comment]
Unit tests are in a pretty good state with upcoming 2.0.
Regarding form validation (expired, invalid Luhn) I've opened a new issue #134
