### ISSUE TITLE
Improve language/terminology of classes/functions/variables

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#48]
Because there are multiple aspects that do much the same thing, there is some crossover of terms. This can make debugging and understanding the code quite difficult.

Below are terms to better clarify in code:

## Response
 * omnipay Responses
 * GatewayResponse - used to encapsulate the omnipay response info and aid in redirection
 * SS_HTTPResponse - ss native responses

## Redirect

 * Gateway redirects - to send the user to an offsite gateway website for entering payment creds
 * Application redirects - after SS omnipay processing. Variables are inconsistent for this, eg: `$message->SuccessURL = $data['returnUrl']`

## Identifiers / References
 * Identifier (on PaymentMessage) - Internally random generated string for uniquely referencing the payment in url.
 * TransactionReference - function on omnipay responses .... ?

## Messages
 * PaymentMessage vs
 * Guzzle Message

@chillu - feel free to add your 2c to help make this clearer, or propose changes.

**Comment by bummzack** [comment]
This has been slightly improved with 2.0.
`GatewayResponse` becomes `ServiceResponse` and the distinction of the redirects should also be clearer/better documented.
Success/Failure URLs have been added to the Payment model.
Closing this for now.
