### ISSUE TITLE
Static return urls don't work when using off-site gateways

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#64]
If a gateway doesn't support dynamic return urls, then this module currently won't work.

A solution to this is to implement your own `PaymentGatewayController` to look up a transaction/payment, based on the data that is passed back.

Another option could possibly be to store a payment id in the session, which is then referenced on return. This probably has implications.

**Comment by toddvalentine** [comment]
Ran into this using the Auth.net SIM Gateway. You have to set a static url for return/notify urls and couldn't use the dynamic urls - paymentendpoint/{transactionid}/complete, etc - because the notify/cancel urls need to be set in the Auth.net interface.

**Comment by bummzack** [comment]
I think the most pragmatic approach is the one outlined above by Jeremy. 

To reduce the possible attack vectors, the endpoint should only be enabled on demand (eg. via config for a certain Gateway).

@toddvalentine would you feel comfortable implementing this, together with some unit-tests?

**Comment by mlewis-everley** [comment]
I have done some work on this (pull request #177), I am not 100% sure about the implementation, it does require the developer to implement their own extension of `PaymentGatewayController` in order to make use of the additional functionality (and set a `use_static_route: true` config variable against the payment gateway).

**Comment by bummzack** [comment]
Implemented (thanks @mlewis-everley) and released as [2.4.0](https://github.com/silverstripe/silverstripe-omnipay/releases/tag/2.4.0)
