### ISSUE TITLE
Administrate/clean incomplete/abandoned payments. Avoid over-payments.

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#66]
Some payments fail, so they show up as "Authorized" or "Created". Payments should not remain in these statuses. Sometimes these payments may have actually succeeded in the gateway.

There are a few ways to clean these up:

 * Administrators should be able to run the 'completePayment' function so to do a lookup that either voids the payment, or completes it.
 * Administrators should be able to complete/void manual payments. Replaces #51
 * Automatic task can tidy up payments that are older than X period.
 * When a payment is re-attempted on the same `Payable` object, it could check if incomplete payments were successful.

**Comment by bummzack** [comment]
Completing payments is possible with 2.0 and the [omnipay-ui module](https://packagist.org/packages/bummzack/silverstripe-omnipay-ui)
Deleting pending payments upon re-attempting is a tricky one… especially with gateways that use async notifications to notify of payment completion. Maybe better not do that…

Closing this and adding a follow up issue: #135
