### ISSUE TITLE
Notify request handling needs to be resolved

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#68]
Gateway servers doing a notify callback will run in a new session.
Currently it will execute whatever it can as if it were the customer. That means redirect urls will potentially be called.

This module should introduce some way to tell if a `completePurchase` request has come from an external gateway server, and act accordingly.

This issue is not documented well

**Comment by bummzack** [comment]
Closed via #107 where async callbacks are supported.
