### ISSUE TITLE
Payable data mapping to ominpay fields

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#74]
Omnipay library and gateways define their fields (parameters), and this is non-negotiable.

Need to provide a mechanism to easily map fields from given data / Payable into omnipay parameters.

**Comment by bummzack** [comment]
I noticed that the omnipay `CreditCard` object will be populated with address-fields, but lacks firstname, lastname and email fields. Is this a separate issue or will this be resolved with this issue?

**Comment by bummzack** [comment]
Closing this, since PaymentController was abandoned. The work that went into PaymentController might be a good thing for a separate Module though.
