### ISSUE TITLE
PaymentController should adjust, based on available gateways

### ISSUE THREAD

**Issue by jedateach** [silverstripe/silverstripe-omnipay#75]
If there is only one gateway, then there is no need to select a gateway.

If a gateway is off-site, then there isn't much need to display a step where the user clicks 'make payment'. If we end up skipping the index view, then it should only be done if there are no previously failed payments. That is because a failed off-site payment could return to the merchant site, and then automatically redirect back to the external gateway....which may be a confusing user experience.

**Comment by bummzack** [comment]
Closing this, since PaymentController was abandoned.
