### ISSUE TITLE
Composer omnipay include causes issue with thirdparty gateways

### ISSUE THREAD

**Issue by webtorque7** [silverstripe/silverstripe-omnipay#82]
I'm not an expert in composer so maybe there is a way around this. When including this module it uses omnipay/omnipay. The issue arises if you then add a thirdparty payment gateway (in my case Alipay) which requires omnipay/common. This ends up installing a separate copy of omnipay/common (likely a different version as well) inside the vendor folder so you end up with two separate copies of omnipay/common.

On a side not, by including omnipay/omnipay you end up with all the payment gateways, when likely you only want one or two. Guess there a pros and cons to this though.

**Comment by JorisDebonnet** [comment]
I think the problem is that these newer payment gateways are built on Omnipay 2, while this package requires Omnipay 1.1... they don't seem to be compatible. It's been a todo for a while to update this to Omnipay 2, see #23.

**Comment by markguinn** [comment]
There is now a 2.0 branch that works with Omnipay 2 and only includes omnipay/common. Just a warning that the branch might fluctuate a bit between now and it's release, and also that Shop might complain as it's currently requiring ~1.1. In the mean time you can use the following in your composer.json to pull this in. Note that you'll have to also include any payment gateways you want via composer as well.

```
"burnbright/silverstripe-omnipay": "2.0.x-dev as 1.1",
```
